/* eslint-disable @next/next/no-img-element */

import type { NextPage } from "next";
import Head from "next/head";
import Background from "./../components/Background/Background";
import homeBackground from "../public/images/headers/header-home.png";
import Hero from "./../components/Hero/Hero";
import Container from "../components/Container/Container";
import { useContext } from "react";
import { LanguagesContext } from "../context/LanguageContext/LanguageContext";

const Home: NextPage = () => {
  const lang = useContext(LanguagesContext);

  console.log(lang);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="home__hero">
        <Background
          src="/images/headers/header-home.png"
          alt="Image de fond accueil de teamdoc"
          className="header__home"
        >
          <img
            src="/images/hero/hero-home.png"
            alt="Deux téléphone, décrivant l'application teamdoc"
            className="home__image"
          />
          <Hero style={{ height: 500 }}>
            <Container>
              <div className="home__container">
                <h1 className="home__title">
                  {`L’application sécurisée dédiée à la communication et
                l'organisation entre soignants`}
                </h1>
                <p className="home__paragraph">
                  {`Créée par des soignants, Team'Doc facilite le travail en équipe
                pour tous les professionnels de santé, à l'hôpital, en clinique
                ou en cabinet.`}
                </p>
                <div className="home__buttons">
                  <button>Telecharger {"=>"}</button>
                  <button>En savoir plus</button>
                </div>
              </div>
            </Container>
          </Hero>
        </Background>
      </section>
      <div style={{ width: "100%", height: 5000 }}></div>
    </>
  );
};

export default Home;
