/* eslint-disable @next/next/no-img-element */

import type { NextPage } from "next";
import { GetStaticProps } from "next";
import Head from "next/head";
import Background from "./../components/Background/Background";
import Hero from "./../components/Hero/Hero";
import Container from "../components/Container/Container";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Partners from "../components/Partners/Partners";
import Button from "./../components/Button/Button";
import Simplification from "../components/Simplification/Simplification";

interface IProps {
  locale: string;
}

const Home = ({ locale }: IProps) => {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="home__hero">
        <Background
          src="/images/headers/header-home.png"
          alt="Image de fond accueil de teamdoc"
          className="header__home"
        >
          <img
            src="/images/hero/hero-home.png"
            alt="Deux téléphone, décrivant l'application teamdoc"
            className="home__image"
          />
          <Hero>
            <Container>
              <div className="home__container">
                <h1 className="home__title">
                  {`L’application sécurisée dédiée à la communication et
                l'organisation entre soignants`}
                </h1>
                <p className="home__paragraph">
                  {`Créée par des soignants, Team'Doc facilite le travail en équipe
                pour tous les professionnels de santé, à l'hôpital, en clinique
                ou en cabinet.`}
                </p>
                <div className="home__buttons">
                  <Button className="button__gradient">
                    Telecharger {"=>"}
                  </Button>
                  <Button className="button__more">En savoir plus</Button>
                </div>
              </div>
            </Container>
          </Hero>
        </Background>
      </section>
      <Simplification />
      <div style={{ width: "100%", height: 800 }}></div>
      <Partners />
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale!, ["home"])),
    },
  };
};

export default Home;
